### ISSUE TITLE
Auto-localized warnings constructor bug on Lady

### ISSUE THREAD

**Issue by Zidras** [Barsoomx/DBM-wowcircle#2]
![image](https://user-images.githubusercontent.com/10605951/95866771-3dd01280-0d60-11eb-9bf1-061fc106ee01.png)

Looking at this code and comparing to retail but couldn't pinpoint the cause of bug.
https://github.com/Barsoomx/DBM-wowcircle/blob/c3406f58011d6ef0ee637c35906bd2fa3efc03ef/DBM-Core/DBM-Core.lua#L4096-L4141

**Comment by Barsoomx** [comment]
fixed it with 1295e0b9 and c3406f58
